language: node_js

sudo: false

node_js:
  - "8"
  - "9"
  - "10"

matrix:
  fast_finish: true

branches:
  only:
    - master

before_script:
  - yarn global add tuture-renderer

script:
  - yarn lint
  - yarn test

cache:
  yarn: true
