environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"

matrix:
  fast_finish: true

branches:
  only:
    - master

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - git config --global user.email "dev@tuture.io"
  - git config --global user.name "Tuture Authors"
  - yarn global add tuture
  - yarn

build: off

test_script:
  - yarn lint
  - yarn test

version: "{build}"
